version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:7

    steps:
      - checkout

      - run:
          name: Install Globals
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash;
            curl -sL https://sentry.io/get-cli/ | bash;

      - run:
          name: Global Config
          command: |
            mkdir ~/.yarn-cache;
            yarn config set cache-folder ~/.yarn-cache;

      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: iInstall Dependencies
          command: yarn install --pure-lockfile

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn-cache
            - node_modules

      - run:
          name: Building
          command: yarn build

      - store_artifacts:
          path: dist/
          destination: build

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              sentry-cli releases new "${CIRCLE_BUILD_NUM}";
              sentry-cli releases set-commits "${CIRCLE_BUILD_NUM}" --auto;
              yarn deploy;
              sentry-cli releases files "${CIRCLE_BUILD_NUM}" upload-sourcemaps dist/ --ext map;
              sentry-cli releases finalize "${CIRCLE_BUILD_NUM}";
              sentry-cli releases deploys "${CIRCLE_BUILD_NUM}" new -e prod;
            fi
