workspace_root: &workspace_root /tmp/workspace

setup_job: &setup_job
    working_directory: *workspace_root
    docker:
      - image: circleci/node:7

version: !!float 2.0

jobs:
  build:
    <<: *setup_job

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Building
          command: yarn build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/
            - dist/

      - store_artifacts:
          path: dist/
          destination: build

  deploy:
    <<: *setup_job

    steps:
      - checkout

      - attach_workspace:
          at: *workspace_root

      - run:
          name: Install Globals
          command: curl -sL https://sentry.io/get-cli/ | bash;

      - deploy:
          name: Deploy
          command: |
            sentry-cli releases new "${CIRCLE_BUILD_NUM}";
            sentry-cli releases set-commits "${CIRCLE_BUILD_NUM}" --auto;
            yarn deploy;
            sentry-cli releases files "${CIRCLE_BUILD_NUM}" upload-sourcemaps dist/ --ext map;
            sentry-cli releases finalize "${CIRCLE_BUILD_NUM}";
            sentry-cli releases deploys "${CIRCLE_BUILD_NUM}" new -e prod;

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: release
          requires:
            - build

