baseURL = "https://marais.io"

title = "Marais Rossouw"
languageCode = "en"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
relativeURLs = false

publishDir = "dist"

disableAliases = true
disableKinds = ["RSS", "term", "taxonomy"]

[taxonomies]
  tag = "tags"

enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.7

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.parser]
			autoHeadingID = false
	[markup.highlight]
		tabWidth = 4
		style = "monokailight"
		codeFences = true
		guessSyntax = true
		lineNumbersInTable = true
		noClasses = false
		noHl = true
		lineNoStart = 1
		lineNos = false
		anchorLineNos = true
		hl_Lines = ""

[imaging]
	hint = "drawing"
	quality = 80
	resampleFilter = "Lanczos"
