baseURL = "https://marais.io"

title = "Marais Rossouw"
languageCode = "en"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
relativeURLs = true

publishDir = "dist"

disableAliases = true
disableKinds = ["RSS", "term", "taxonomy", "categories"]

[taxonomies]
  tag = "tags"

enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.7

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
	[markup.highlight]
		tabWidth = 2
		style = "github"
		codeFences = true
		guessSyntax = true
		lineNumbersInTable = true
		noClasses = false
		lineNoStart = 1
		lineNos = false
		hl_Lines = ""